---

- name: VM Creation
  hosts: vsphere
  gather_facts: False
  vars_prompt:
    - name: "vcenter_host"
      prompt: "Please introduce vCenter IP address"
      private: no
    - name: "vcenter_user"
      prompt: "Please introduce vCenter username"
      private: no
    - name: "vcenter_pass"
      prompt: "Please introduce vCenter password"
  roles:
    - vsphere

